services:
  main-app:
    working_dir: /app/src
    environment:
      - PYTHONPATH=/app/src
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    command: uvicorn --factory main:create_app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - sqlite_data:/app/src/data
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env.dev

volumes:
  sqlite_data:

