version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ../docker-compose/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
    networks:
      - complaints_app_network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin1
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - complaints_app_network

networks:
  default:
    external: true
    name: complaints_app_network
